package com.mycompany.prueba;
// Generated 7/05/2019 01:45:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String contrasenia;
     private String correo;
     private Integer rol;
     private Set comentarios = new HashSet(0);
     private Set marcadors = new HashSet(0);
     private Set temas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String nombre, String contrasenia, String correo) {
        this.idusuario = idusuario;
        this.nombre = nombre;
        this.contrasenia = contrasenia;
        this.correo = correo;
    }
    public Usuario(int idusuario, String nombre, String apaterno, String amaterno, String contrasenia, String correo, Integer rol, Set comentarios, Set marcadors, Set temas) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.contrasenia = contrasenia;
       this.correo = correo;
       this.rol = rol;
       this.comentarios = comentarios;
       this.marcadors = marcadors;
       this.temas = temas;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getRol() {
        return this.rol;
    }
    
    public void setRol(Integer rol) {
        this.rol = rol;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }

    public String toString(){
        return this.correo;
    }


}


