package modelo;
// Generated 26/03/2019 05:09:40 PM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int idComentario;
     private Marcador marcador;
     private Usuario usuario;
     private float calificacion;

    public Comentario() {
    }

    public Comentario(int idComentario, Marcador marcador, Usuario usuario, float calificacion) {
       this.idComentario = idComentario;
       this.marcador = marcador;
       this.usuario = usuario;
       this.calificacion = calificacion;
    }
   
    public int getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(int idComentario) {
        this.idComentario = idComentario;
    }
    public Marcador getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(Marcador marcador) {
        this.marcador = marcador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public float getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(float calificacion) {
        this.calificacion = calificacion;
    }




}


