package modelo;
// Generated 30/03/2019 12:03:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idMarcador;
     private Tema tema;
     private String tema1;
     private String correo;
     private Usuario usuario;
     private Double latitud;
     private Double longitud;
     private String descripcion;
     private String datos;
     private Set comentarios = new HashSet(0);

    public Marcador() {
    }

	
    public Marcador(int idMarcador, Tema tema, Usuario usuario) {
        this.idMarcador = idMarcador;
        this.tema = tema;
        this.usuario = usuario;
    }
    public Marcador(int idMarcador, Tema tema, Usuario usuario, Double latitud, Double longitud, String descripcion, String datos, Set comentarios) {
       this.idMarcador = idMarcador;
       this.tema = tema;
       this.usuario = usuario;
       this.latitud = latitud;
       this.longitud = longitud;
       this.descripcion = descripcion;
       this.datos = datos;
       this.comentarios = comentarios;
    }
   
    public int getIdMarcador() {
        return this.idMarcador;
    }
    
    public void setIdMarcador(int idMarcador) {
        this.idMarcador = idMarcador;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    
    public void setTema(String tema1) {
        this.tema1 = tema1;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;  
    }

    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDatos() {
        return this.datos;
    }
    
    /**
     *
     * @param datos
     */
    public void setDatos(String datos) {
        this.datos = datos;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }

    public void setUsuario(String a) {
        this.correo=a;
    }




}


