package modelo;
// Generated 26/03/2019 05:09:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private int idTema;
     private Usuario usuario;
     private String nombre;
     private Set marcadors = new HashSet(0);

    public Tema() {
    }

	
    public Tema(int idTema, Usuario usuario) {
        this.idTema = idTema;
        this.usuario = usuario;
    }
    public Tema(int idTema, Usuario usuario, String nombre, Set marcadors) {
       this.idTema = idTema;
       this.usuario = usuario;
       this.nombre = nombre;
       this.marcadors = marcadors;
    }
   
    public int getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }




}


