package modelo;
// Generated 30/03/2019 12:03:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private String nombre;
     private Usuario usuario;
     private Set marcadors = new HashSet(0);

    public Tema() {
    }

	
    public Tema(String nombre, Usuario usuario) {
        this.nombre = nombre;
        this.usuario = usuario;
    }
    public Tema(String nombre, Usuario usuario, Set marcadors) {
       this.nombre = nombre;
       this.usuario = usuario;
       this.marcadors = marcadors;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }




}


