package modelo;
// Generated 7/05/2019 01:45:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private String nombre;
     private Usuario usuario;
     private String color;
     private Set marcadors = new HashSet(0);

    public Tema() {
    }

	
    public Tema(String nombre, Usuario usuario) {
        this.nombre = nombre;
        this.usuario = usuario;
    }
    public Tema(String nombre, Usuario usuario, String color, Set marcadors) {
       this.nombre = nombre;
       this.usuario = usuario;
       this.color = color;
       this.marcadors = marcadors;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }


    public String toString(){
        return this.getNombre();
    }
}


