package modelo;
// Generated 30/03/2019 12:03:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correo;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String contrasenia;
     private String rol;
     private Set temas = new HashSet(0);
     private Set marcadors = new HashSet(0);
     private Set comentarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String correo, String nombre, String contrasenia, String rol) {
        this.correo = correo;
        this.nombre = nombre;
        this.contrasenia = contrasenia;
        this.rol = rol;
    }
    public Usuario(String correo, String nombre, String apaterno, String amaterno, String contrasenia, String rol, Set temas, Set marcadors, Set comentarios) {
       this.correo = correo;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.contrasenia = contrasenia;
       this.rol = rol;
       this.temas = temas;
       this.marcadors = marcadors;
       this.comentarios = comentarios;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


